"""
Zoning Language Agent.
Generates full draft ordinance text for permitted uses, overlay zones, and dimensional standards.
"""

from .base import call_llm, parse_json_response
try:
    from .. import config
except ImportError:
    import config


def _mock_zoning(inputs: dict, tier: int) -> dict:
    state = inputs.get("state", "the State")
    density = inputs.get("density", "suburban")
    municipality = inputs.get("municipality") or "the Municipality"
    scale = inputs.get("operational_scale", 100)

    # Determine base zone compatibility
    if density in ("rural", "suburban"):
        permitted_zones = ["I-1 (Light Industrial)", "I-2 (General Industrial)", "C-3 (General Commercial)"]
        conditional_zones = ["C-2 (Neighborhood Commercial)", "M-1 (Business Park)"]
        prohibited_zones = ["R-1", "R-2", "R-3 (Residential)", "OS (Open Space)"]
    else:
        permitted_zones = ["I-1", "I-2", "C-3", "C-4 (Regional Commercial)", "MU-3 (Mixed Use — High Intensity)"]
        conditional_zones = ["C-2", "M-1", "MU-1", "MU-2 (Mixed Use — Moderate)"]
        prohibited_zones = ["R-1", "R-2 (Residential — Low Density)"]

    overlay = f"UAM-O{tier} Overlay District"
    hours = "0600–2200 local time" if tier <= 2 else "0500–2300 local time" if tier == 3 else "24-hour operations subject to noise conditions"

    text = f"""SECTION 1. PURPOSE AND INTENT

The {municipality} City Council finds that drone hubs and vertiport facilities represent emerging infrastructure
critical to regional transportation, logistics, and economic development. This Article establishes standards
to permit such facilities in appropriate locations while protecting public health, safety, and neighborhood character,
consistent with applicable {state} state law and Federal Aviation Administration regulations.

SECTION 2. APPLICABILITY

This Article applies to all Drone Hubs and Vertiports as defined in Article II, including new construction,
expansion of existing facilities by more than 10% of pad area, and any change in operational tier classification.

SECTION 3. OVERLAY DISTRICT — {overlay}

(a) The {overlay} may be applied to parcels in the following base zones by action of the Planning Commission:
    Permitted-by-right zones: {', '.join(permitted_zones)}.
    Conditional use permit required: {', '.join(conditional_zones)}.
    Prohibited: {', '.join(prohibited_zones)}.

(b) Application of the {overlay} requires a separate overlay application concurrent with, or prior to, any
    discretionary land use entitlement for the facility.

SECTION 4. PERMITTED USES

Within the {overlay} Overlay District, the following uses are permitted subject to the standards of this Article:
    (1) Landing pads, take-off areas, and associated taxi routes for UAS and eVTOL aircraft.
    (2) Ground Support Infrastructure (GSI), including battery charging, fuel cell servicing, and aircraft storage.
    (3) On-site operations control center and communications equipment.
    (4) {'Passenger waiting areas and intermodal connection facilities.' if tier >= 3 else 'Package sorting and staging areas for delivery operations.'}
    (5) Accessory retail and food service not exceeding 2,000 sq ft (Tier 3–4 only).

SECTION 5. DEVELOPMENT STANDARDS

(a) Maximum pad height: {'15 ft above finished grade for ground-level facilities; rooftop installations to be evaluated per structural review.' if tier <= 2 else '35 ft above finished grade or existing structure height, whichever is greater.'}
(b) Maximum GSI building height: {'25 ft' if tier <= 2 else '50 ft'}.
(c) Lighting: All lighting shall be fully shielded, downward-directed, and compliant with FAA Advisory Circular 150/5345-43.
(d) Hours of operation: {hours}.
(e) Noise: Noise generated by aircraft operations and GSI shall not exceed {55 if density in ('rural','suburban') else 65} dB(A) Leq at the nearest noise-sensitive receptor, measured at the property line.

SECTION 6. SIGNAGE

All signage shall comply with the base zone standards. Additionally, all facilities shall display:
    (1) FAA-required facility identification markings.
    (2) A publicly visible placard indicating the facility's tier, operating hours, and emergency contact.

SECTION 7. NONCONFORMING FACILITIES

Any UAS or eVTOL facility lawfully established prior to the effective date of this Article shall be deemed
a nonconforming use and may continue operations, subject to the following: any expansion triggering
re-classification to a higher tier shall require full compliance with this Article."""

    return {
        "text": text,
        "permitted_zones": permitted_zones,
        "conditional_zones": conditional_zones,
        "prohibited_zones": prohibited_zones,
        "overlay_district": overlay,
        "operating_hours": hours,
        "noise_limit_dba": 55 if density in ("rural", "suburban") else 65,
        "notes": (
            f"Zoning language drafted for Tier {tier} facility in {density} context, {state}. "
            "Hours of operation and noise limits should be verified against local noise ordinances and {state} state aviation preemption statutes."
        ),
    }


def _build_prompt(inputs: dict, tier: int) -> str:
    return f"""You are a land-use attorney drafting zoning ordinance text for a Tier {tier} drone hub or vertiport in {inputs.get('municipality', inputs.get('state', 'a U.S. municipality'))}.

PROJECT PARAMETERS:
{inputs}

Draft complete ordinance sections covering:
1. Purpose and intent
2. Applicability
3. Overlay district establishment and eligible base zones
4. Permitted uses table
5. Development standards (height, lighting, noise, hours of operation)
6. Signage
7. Nonconforming facilities

Return a JSON object with:
- text: the full multi-section ordinance draft as a string
- permitted_zones: list of zones where this is permitted by right
- conditional_zones: list of zones requiring a CUP
- prohibited_zones: list of prohibited zone types
- overlay_district: name string
- operating_hours: string
- noise_limit_dba: number
- notes: string

Return only valid JSON."""


class ZoningAgent:
    def generate(self, inputs: dict, tier: int = 2) -> dict:
        api_live = __import__("os").environ.get("ANTHROPIC_API_KEY") or __import__("os").environ.get("OPENAI_API_KEY")
        if not api_live:
            return _mock_zoning(inputs, tier)

        prompt = _build_prompt(inputs, tier)
        response = call_llm(prompt, role="zoning_agent", max_tokens=4096)
        result = parse_json_response(response)
        if result.get("mock") or result.get("parse_error"):
            return _mock_zoning(inputs, tier)
        return result
