"""
Export ordinance package to Markdown.
"""

import os
from datetime import datetime


def export_ordinance(session, export_dir: str) -> str:
    """Assemble all ordinance components into a single Markdown document."""
    os.makedirs(export_dir, exist_ok=True)

    i = session.inputs
    o = session.outputs
    municipality = i.get("municipality") or i.get("state", "Municipality")
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    filename = f"ordinance_{municipality.replace(' ', '_')}_{timestamp}.md"
    filepath = os.path.join(export_dir, filename)

    lines = []

    lines.append(f"# Drone Hub & Vertiport Zoning Ordinance")
    lines.append(f"## {municipality}")
    lines.append(f"*Generated: {datetime.utcnow().strftime('%B %d, %Y')}*")
    lines.append("")
    lines.append("---")
    lines.append("")

    # --- Inputs summary ---
    lines.append("## Project Parameters")
    lines.append("")
    lines.append(f"| Parameter | Value |")
    lines.append(f"|-----------|-------|")
    lines.append(f"| State | {i.get('state', '—')} |")
    lines.append(f"| Airport Type | {i.get('airport_type', '—')} |")
    lines.append(f"| Density Context | {i.get('density', '—')} |")
    lines.append(f"| Operational Scale | {i.get('operational_scale', '—')} ops/day |")
    lines.append(f"| Site Acreage | {i.get('site_acreage', '—')} acres |")
    lines.append("")

    # --- Tier Classification ---
    _append_section(lines, "Article I — Tier Classification", o.get("tier_classification", {}))

    # --- Use Definitions ---
    _append_section(lines, "Article II — Definitions", o.get("use_definitions", {}))

    # --- Zoning Language ---
    _append_section(lines, "Article III — Zoning Language", o.get("zoning_language", {}))

    # --- Setback Recommendations ---
    _append_section(lines, "Article IV — Setback Requirements", o.get("setback_recommendations", {}))

    # --- Approval Pathways ---
    _append_section(lines, "Article V — Approval Pathways", o.get("approval_pathways", {}))

    # --- Environmental Review Triggers ---
    _append_section(lines, "Article VI — Environmental Review", o.get("environmental_triggers", {}))

    lines.append("---")
    lines.append("*This document was generated by the Drone Hub / Vertiport Ordinance Agent.*")
    lines.append("*It is a starting point for legal review and should not be adopted without counsel.*")

    content = "\n".join(lines)
    with open(filepath, "w", encoding="utf-8") as fh:
        fh.write(content)

    return filepath


def _append_section(lines: list, heading: str, data: dict):
    lines.append(f"## {heading}")
    lines.append("")
    if not data:
        lines.append("*Not yet generated.*")
        lines.append("")
        return

    # Text body
    body = data.get("text") or data.get("content") or data.get("language") or ""
    if body:
        lines.append(body)
        lines.append("")

    # Structured items (list of dicts)
    items = data.get("items") or data.get("definitions") or data.get("pathways") or []
    for item in items:
        if isinstance(item, dict):
            label = item.get("label") or item.get("name") or item.get("term") or ""
            detail = item.get("detail") or item.get("definition") or item.get("description") or ""
            if label:
                lines.append(f"**{label}**")
            if detail:
                lines.append(detail)
            lines.append("")
        elif isinstance(item, str):
            lines.append(f"- {item}")

    notes = data.get("notes") or data.get("rationale") or ""
    if notes:
        lines.append(f"> *Note: {notes}*")
        lines.append("")
